:filetype on
":filetype off
:filetype indent on

:setlocal cino=(0

:set nu 
:set ai 
:set sw=4 
:set ts=4 
:set hls 
:set incsearch 
:set ruler 
:set showmatch 
:set guioptions-=T
:set smartindent
:set backspace=indent,eol,start
:set nocompatible
:set guifont=Monospace\ 9
:set background=dark
:set expandtab
:set mouse=r

:highlight Normal  guifg=yellow guibg=black 
:highlight Search  guifg=white  guibg=blue 
:highlight Visual  guifg=blue   guibg=yellow 
:highlight comment guifg=cyan

:syntax on

:set showtabline=2

:set backupdir=~/.vimbak
:set directory=~/.vimswp

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

:function! TabpageName(mode)
:    if a:mode == 1
:        return fnamemodify(expand("%"), ":p:h")
:    elseif a:mode == 2
:        let name = fnamemodify(expand("%"), ":p:t")
:            if name == ""
:            return "(Untitled)"
:        endif
:        return name
:    endif
:endfunction

:function! TabpageState()
:    if &modified != 0
:        return '*'
:    else
:        return ''
:    endif
:endfunction

:set guitablabel=%{TabpageName(2)}%{TabpageState()}

