#!/bin/bash

stop() {
    echo "Stopping..."
}

start() {
    echo "Starting..."

    /sbin/sysctl -p

    /usr/bin/pkill ensure-dnsmasq
    /etc/init.d/ensure-dnsmasq &
}

restart() {
    stop
    start
}

case $1 in
    stop)
        stop
        ;;
    start)
        start
        ;;
    restart)
        restart
        ;;
esac

