#!/bin/bash

export PATH=${PATH}:/usr/local/bin

echo "`date`  Running mega-cmd-server [$1]"

start() {
    echo "`date`  Starting mega-cmd-server"
    cd /root
    rm -rf /root/.megaCmd/*db*
    /usr/local/bin/mega-sync &
}

stop() {
    echo "`date`  Stopping mega-cmd-server"
    /usr/bin/pkill mega-sync
    /usr/bin/pkill mega-cmd-server
    rm -rf /root/.megaCmd/*db*
}

restart() {
    echo "`date`  Restarting mega-cmd-server"
    stop
    start
}

case $1 in
    stop)
        stop
        ;;
    start)
        start
        ;;
    restart)
        restart
        ;;
esac

echo "`date`  Done running mega-sync..."

ps aux | grep mega | grep -v grep

exit 0
